<a href="https://colab.research.google.com/github/swagatamr/NLP-classification-to-predict-type-of-question/blob/main/NLP_Classification_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
from google.colab import files
files.upload()

In [ ]:
import re
import nltk.corpus
import pandas as pd
import numpy as np


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [ ]:
df.to_excel("labeled data.xlsx",header=True)

In [ ]:
from google.colab import files
files.upload()

Saving labeled data.xlsx to labeled data (2).xlsx


{'labeled data.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xc8\xa3\xcd4v\x01\x00\x00\x04\x05\x00\x00\x13\x00\xdd\x01[Content_Types].xml \xa2\xd9\x01(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [ ]:
df1=pd.read_excel("labeled data (2).xlsx")

In [ ]:
df1.shape

(1483, 2)

In [ ]:
df1

Text         Label
0     how did serfdom develop in and then leave russ...       unknown
1     what films featured the character popeye doyle ?           what
2     how can i find a list of celebrities ' real na...       unknown
3     what fowl grabs the spotlight after the chines...          what
4                      what is the full form of .com ?           what
...                                                 ...           ...
1478                            can it be cut to fit ?    affirmation
1479                               can it be removed ?    affirmation
1480                         does this hose have one ?    affirmation
1481                           can i get it in india ?    affirmation
1482  would this work on a 2008 ford edge with a nak...   affirmation

[1483 rows x 2 columns]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1483 entries, 0 to 1482
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Text    1483 non-null   object
 1   Label   1483 non-null   object
dtypes: object(2)
memory usage: 23.3+ KB


In [ ]:
df1.columns

Index(['Text', 'Label'], dtype='object')

In [ ]:
df1['Label'].unique()

array([' unknown', ' what', ' when', ' who', '  what', '  who',
       ' affirmation'], dtype=object)

In [ ]:
df1.columns

Index(['Text', 'Label'], dtype='object')

In [ ]:
df1['Text'] = df1['Text'].apply(lambda x: x.lower())
df1['Text'] = df1['Text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))

In [ ]:
df1

Text         Label
0     how did serfdom develop in and then leave russ...       unknown
1      what films featured the character popeye doyle            what
2     how can i find a list of celebrities  real nam...       unknown
3     what fowl grabs the spotlight after the chines...          what
4                        what is the full form of com            what
...                                                 ...           ...
1478                             can it be cut to fit     affirmation
1479                                can it be removed     affirmation
1480                          does this hose have one     affirmation
1481                            can i get it in india     affirmation
1482  would this work on a 2008 ford edge with a nak...   affirmation

[1483 rows x 2 columns]

In [ ]:
from collections import Counter, defaultdict
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle as pkl
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from nltk.stem import SnowballStemmer
from nltk import word_tokenize
from nltk.corpus import wordnet as wn

In [ ]:
class StemTokenizer(object):
    def __init__(self):
        self.ignore_set = {'footnote', 'nietzsche', 'plato', 'mr.'}

    def call(self, doc):
        words = []
        for word in word_tokenize(doc):
            word = word.lower()
            w = wn.morphy(word)
            if w and len(w) > 1 and w not in self.ignore_set:
                words.append(w)
        return words

In [ ]:
s = SnowballStemmer('english').stem
def stem_tokenize(text):
    return [s(i) for i in word_tokenize(text)]


In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
vectorizer = CountVectorizer(analyzer='word',lowercase=True,tokenizer=stem_tokenize)
X_train = vectorizer.fit_transform(df1.Text.values)
labels = df1['Label']

In [ ]:
# split the data into a training set and a validation set
indices = np.arange(X_train.shape[0])
np.random.shuffle(indices)
X_train = X_train[indices]
labels = labels[indices]
nb_validation_samples = int(0.20 * X_train.shape[0])

x_train = X_train[:-nb_validation_samples]
y_train = labels[:-nb_validation_samples]
x_val = X_train[-nb_validation_samples:]
y_val = labels[-nb_validation_samples:]

In [ ]:
clf = MultinomialNB()
clf.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
preds = clf.predict(x_val)

In [ ]:
print(preds)

[' who' ' what' ' unknown' ' what' ' who' ' who' ' who' ' what' ' what'
 ' affirmation' ' what' ' what' ' who' ' what' ' unknown' ' unknown'
 ' who' ' unknown' ' what' ' what' ' what' ' unknown' ' what' ' what'
 ' who' ' what' ' who' ' what' ' who' ' what' ' unknown' ' what'
 ' unknown' ' unknown' ' what' ' unknown' ' who' ' what' ' who'
 ' affirmation' ' unknown' ' what' ' what' ' who' ' affirmation' ' what'
 ' unknown' ' what' ' who' ' who' ' what' ' affirmation' ' unknown'
 ' unknown' ' unknown' ' what' ' what' ' what' ' what' ' when' ' unknown'
 ' what' ' unknown' ' what' ' who' ' who' ' what' ' who' ' what' ' what'
 ' what' ' what' ' unknown' ' affirmation' ' what' ' what' ' what' ' what'
 ' affirmation' ' what' ' what' ' what' ' who' ' what' ' when' ' what'
 ' what' ' what' ' what' ' who' ' who' ' what' ' what' ' what' ' what'
 ' who' ' who' ' who' ' what' ' what' ' unknown' ' unknown' ' who' ' who'
 ' unknown' ' what' ' affirmation' ' what' ' what' ' unknown' ' what'
 ' what' ' 

In [ ]:
print(y_val)

533          who
22       unknown
634         what
665         what
1031         who
          ...   
146      unknown
130         what
69          what
471          who
742         what
Name: Label, Length: 296, dtype: object


In [ ]:
print(confusion_matrix(y_val,preds))

[[  0   0   0   0   0   1]
 [  0  21   4   6   0   0]
 [  0   0  48  12   1   3]
 [  0   0   0 111   1   1]
 [  0   0   1  10   6   2]
 [  0   0   0   0   0  68]]


In [ ]:
# evaluate the model of test data
preds = clf.predict(x_val)
print(classification_report(preds,y_val))
print("Accuracy :",clf.score(x_val,y_val))

              precision    recall  f1-score   support

 affirmation       0.71      1.00      0.83        15
     unknown       0.81      0.89      0.85        47
        what       0.99      0.88      0.93       151
        when       0.44      0.88      0.58         8
         who       1.00      0.96      0.98        75

    accuracy                           0.91       296
   macro avg       0.79      0.92      0.83       296
weighted avg       0.93      0.91      0.92       296

Accuracy : 0.9087837837837838


In [ ]:
example=vectorizer.transform(["What time does the train leave"])
clf.predict(example)

array([' what'], dtype='<U12')

In [ ]:
example=vectorizer.transform(["What is your name?"])
clf.predict(example)

array([' what'], dtype='<U12')

In [ ]:
example=vectorizer.transform(["Is there a cab available for airport?"])
clf.predict(example)

array([' unknown'], dtype='<U12')

In [ ]:
from sklearn import svm
clf1 = svm.SVC()
clf1.fit(x_train,y_train)
preds1 = clf1.predict(x_val)
# evaluate the model of test data
preds1 = clf1.predict(x_val)
print(confusion_matrix(y_val,preds1))
print(classification_report(preds1,y_val))
print("Accuracy :",clf1.score(x_val,y_val))

[[  0   0   0   0   0   1]
 [  0  25   6   0   0   0]
 [  0   0  60   2   0   2]
 [  0   0   0 113   0   0]
 [  0   0   1   5  13   0]
 [  0   0   0   0   0  68]]
              precision    recall  f1-score   support

         who       0.00      0.00      0.00         0
 affirmation       0.81      1.00      0.89        25
     unknown       0.94      0.90      0.92        67
        what       1.00      0.94      0.97       120
        when       0.68      1.00      0.81        13
         who       1.00      0.96      0.98        71

    accuracy                           0.94       296
   macro avg       0.74      0.80      0.76       296
weighted avg       0.96      0.94      0.95       296

Accuracy : 0.9425675675675675


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
example=vectorizer.transform(["What is your name?"])
clf1.predict(example)

array([' what'], dtype=object)

In [ ]:
example=vectorizer.transform(["When is the show happening?"])
clf1.predict(example)

array([' when'], dtype=object)

In [ ]:
example=vectorizer.transform(["Is there a cab available for airport?"])
clf1.predict(example)

array([' affirmation'], dtype=object)